name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app

            # If repo not cloned yet, clone it
            if [ ! -d ".git" ]; then
              git clone https://github.com/vinodpr1/depl.git .
            else
              git pull origin master
            fi

            # Install Node if not installed (optional)
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install dependencies and build
            npm install
            npm run build

            # Restart service (adjust the name)
            sudo systemctl restart my-node-app.service
