name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# env:
#   AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
#   AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
#   AWS_EC2_KEY: ${{ secrets.PRIVATE_KEY }}
#   REPO_URL: https://github.com/vinodpr1/depl.git

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: List files and folders
      run: ls -la
      run: ls